# Generated by Django 6.0.3 on 2026-03-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='code_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='code_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='manual_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='reset_token',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='passwordresetrequest',
            name='token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
