# Generated by Django 6.0.3 on 2026-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_passwordresetrequest_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True),
        ),
    ]
