# Generated by Django 6.0.3 on 2026-03-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_middle_name_patient_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
